version: '3.8'
services:
  users:
    container_name: users
    build:
      context: ./services/users
      dockerfile: Dockerfile-dev
    
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=manage.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@users-db:5432/users_test

    depends_on:
      - users-db
    links:
      - users-db

  users-db:
    container_name: users-db
    build: 
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

